/**
 * The card's colours, read out of the design system rather than typed here.
 *
 * ⭐ THIS IS THE DRIFT MITIGATION. The card is Typst markup, not an Astro page,
 * so it does not inherit the site's CSS the way every other surface does. That
 * was the one real cost of choosing Typst (plan §0), and this closes most of
 * it: every colour comes from src/styles/tokens/colors.css, which sync-tokens
 * copies from ~/aikyam-space-design-system before every build. Change a token
 * there and the next card carries it.
 *
 * ⚠️ It covers COLOUR only. The type scale and spacing are still written into
 * card.typ by hand, because Typst's pt/em model and the site's rem/clamp model
 * do not map one to one. A type-scale change in the design system does NOT
 * reach the card on its own.
 *
 * ⛔ Fails loudly on a missing token. A card quietly rendering black-on-white
 * because a variable was renamed is exactly the silent failure this project
 * keeps having to design around.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const COLORS_CSS = path.join(here, '..', 'src', 'styles', 'tokens', 'colors.css');

/** Every token the card and the record actually use. Named so a miss is a
 *  named failure. */
const WANTED = [
  'aik-ink',
  'aik-ink-quiet',
  'aik-paper',
  'aik-paper-sunk',
  'aik-rule',
  'aik-mint',
  /* ⭐ The record PDF's live link in its foot. `--aik-green-ink`, not
     `--aik-green`: the design system carries both because the brand green
     (#008246) does not reach 4.5:1 as TEXT on cream, and this darker walk of
     the same hue does. A printed record is read on cream. ⚠️ Adding a token
     here is safe for the golden card — golden.typ names the colours it draws,
     so an extra `#let` in the generated prelude changes no pixel. */
  'aik-green-ink',
];

export function readTokens() {
  let css;
  try {
    css = readFileSync(COLORS_CSS, 'utf8');
  } catch {
    throw new Error(
      `story: no ${COLORS_CSS}. Run \`npm run sync-tokens\` first — it copies the ` +
        `design system's tokens in, and every build does it before this point.`,
    );
  }

  const out = {};
  for (const name of WANTED) {
    // ⛔ Anchored to a declaration, not a mention: colors.css discusses its own
    // token names in prose comments constantly (`--aik-mint #dcffe6 — the
    // wordmark's "space"`), and a looser pattern picks the comment up first.
    const m = css.match(new RegExp(`^\\s*--${name}:\\s*(#[0-9a-fA-F]{3,8})\\s*;`, 'm'));
    if (!m) throw new Error(`story: --${name} not found in ${COLORS_CSS}`);
    out[name] = m[1];
  }
  return out;
}

/** The same values as a Typst prelude, so card.typ never hard-codes a hex. */
export function tokensAsTypst(tokens) {
  const lines = Object.entries(tokens).map(
    ([name, hex]) => `#let ${name.replace(/-/g, '_')} = rgb("${hex}")`,
  );
  return `// GENERATED by story/lib/tokens.mjs from src/styles/tokens/colors.css.\n` +
    `// Do not edit: change the token in the design system instead.\n${lines.join('\n')}\n`;
}
